### ISSUE TITLE
Unable to install airflow-provider-kafka package in Azure Cloud Airflow VM instance

### ISSUE THREAD

**Issue by Bindu-yadav8** [astronomer/airflow-provider-kafka#19]
While executing the command " pip install airflow-provider-kafka" in the airflow instance in the VM, seeing an error message as below:

<img width="958" alt="image" src="https://user-images.githubusercontent.com/86333293/208846069-26ea2d5f-e3fd-4d26-94ab-3975cb80029c.png">

Airflow version  - 2.2.5
Python Version - 3.6 and pip version 21.3.1

Also, I observed that this was released in the last week, any version compatibility is causing this issue? Anybody please suggest on this.

**Comment by AlexandrChikur** [comment]
@Bindu-yadav8 Hi, you sayin that u are use 3.6 version of python. 
As described in `setup.cfg` of `airflow-provider-kafka`:
https://github.com/astronomer/airflow-provider-kafka/blob/5cc531388bc0190402b104344856be94b2466649/setup.cfg#L28
It's required python version `3.7` or greater, could be this is causing issue? 
Actually, not sure if im right, but would you try to install it on this python version ?
