### ISSUE TITLE
Kafka use connection_id as connectionString

### ISSUE THREAD

**Issue by BrandeeDev** [astronomer/airflow-provider-kafka#20]
Context: kafka_conn_id parameters with KafkaProducer.

Issue: KafkaProducerHook use kafka_conn_id as connectionString 
```

if self.kafka_conn_id:
            conn = self.get_connection(self.kafka_conn_id)
            self.extra_configs = {"bootstrap.servers": conn}
            self.log.info(
                f"Connection ID {self.kafka_conn_id} used for bootstrap servers,"
                + " {extra_configs} added to kafka config."
            )
```
Desired behavior:

```
if self.kafka_conn_id:
            conn = self.get_connection(self.kafka_conn_id)
            self.extra_configs = {"bootstrap.servers": f"{conn.host}:{conn.port}"}
            self.log.info(
                f"Connection ID {self.kafka_conn_id} used for bootstrap servers,"
                + " {extra_configs} added to kafka config."
            )
```
As a solution for the moment. The connection string is the connection_id.
It is not always kafka listen to port 9200.

**Comment by dylanbstorey** [comment]
The connections interface for the operators isn't defined well at this time.  The primary interface is currently to b use the config dictionary in the operator. Please feel free to submit a PR if you'd like to increase this capability.
