### ISSUE TITLE
Getting Errror while using ProduceToTopicOperator() operator

### ISSUE THREAD

**Issue by krshashank963** [astronomer/airflow-provider-kafka#27]
While using ProduceToTopicOperator() operator I am getting following error 

**ERROR - Failed to deliver message: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}**

It seems to be a configuration issue I am using following configuration

```
my_topic = 'demo'
connection_config = {
    
    "bootstrap.servers":'***************' ,
    "security.protocol":'SASL_SSL',
    "sasl.mechanism": "PLAIN",
    "sasl.username":'XU7UGVNZURMP63EH' ,
    "sasl.password": '**************'
```
.

**Comment by dylanbstorey** [comment]
This could be a number of things, I'd start by verifying your bootstrap servers connectivity and topic availability; then progress to timeout options on the config.

Closing as this isn't a great forum for localalized debugging.
