### ISSUE TITLE
Example not working on Airflow 2.0

### ISSUE THREAD

**Issue by roalonsor** [astronomer/airflow-provider-kafka#28]
It would be nice update this example `https://github.com/astronomer/airflow-provider-kafka/blob/main/example_dags/listener_dag_function.py` since it doesn't work on Airflow 2.0, Thanks

**Comment by dylanbstorey** [comment]
This package requires [airflow > 2.2]( https://github.com/astronomer/airflow-provider-kafka/blob/91ab31464a06e3e743751f46b6e9affc7a42ad7f/setup.cfg#L32) as it is reliant on deferrable operators.
