### ISSUE TITLE
Unable to install airflow-provider-kafka package on Azure Cloud Airflow VM instance

### ISSUE THREAD

**Issue by Bindu-yadav8** [astronomer/airflow-provider-kafka#29]
Hello,

We have Airflow version(2.5.1) running in one of the Azure VMs, unable to install the airflow-provider-kafka package. I tried to install it on this python version  3.7.5.   Seeing **Failed building wheel for confluent-kafka**

<img width="947" alt="image" src="https://user-images.githubusercontent.com/86333293/220332695-5846413d-4a6a-405b-ab78-95dd847580d3.png">

<img width="959" alt="image" src="https://user-images.githubusercontent.com/86333293/220332861-85964a83-7811-4ebf-8f6d-4f9b844ac491.png">

<img width="946" alt="image" src="https://user-images.githubusercontent.com/86333293/220333053-4b05989d-c69a-40bf-ac0a-aa860c10effc.png">

<img width="947" alt="image" src="https://user-images.githubusercontent.com/86333293/220333243-84afd4fa-3481-4dfb-9aef-0b9d34042ca4.png">

Anybody please suggest on this. 

@AlexandrChikur

**Comment by dylanbstorey** [comment]
Looks like librdkafka isn't installed on that machine. Check with the confluent installation guides for how to complete this.
