### ISSUE TITLE
Push data from ConsumeFromTopicOperator to XCom

### ISSUE THREAD

**Issue by manojmanivannan** [astronomer/airflow-provider-kafka#33]
Can the messages consumed from ConsumeFromTopicOperator be pushed to XCom ?

**Comment by dylanbstorey** [comment]
Should be possible but as a rule I wouldn't suggest it.

**Comment by manojmanivannan** [comment]
Any suggestions on how to move records from Kafka topics ?
I'm trying to find a solution for this case https://stackoverflow.com/questions/76372178/how-to-push-data-records-from-consumefromtopicoperator-to-xcom

**Comment by dylanbstorey** [comment]
I'd start to see if 

https://airflow.apache.org/docs/apache-airflow-providers-apache-kafka/1.1.0/

Helps you out.  That's the officially supported provider now.

**Comment by manojmanivannan** [comment]
@dylanbstorey  thanks so much. After more digging, I was able to simply the approach and implement using Kafka consumer from kafka-python.
