### ISSUE TITLE
Does not specify minimum required version of Airflow

### ISSUE THREAD

**Issue by MorganRodgers** [astronomer/airflow-provider-kafka#35]
Judging by the requirement to have triggers and deferrables this looks like it requires at least Airflow 2.2.0, but the documentation doesn't list compatible Airflow versions.

A quick statement of the minimum required version, or a range of versions in the readme would be a great help.

**Comment by dylanbstorey** [comment]
Couple of things:
- Versions are pretty clearly [pinned](https://github.com/astronomer/airflow-provider-kafka/blob/ac464de7fef87c8440a67e84f7e630e17dc740da/setup.cfg#L32).
- This repo has been deprecated in favor of one that is being maintained in [airflow](https://airflow.apache.org/docs/apache-airflow-providers-apache-kafka/stable/index.html)
- Especially with something this minor - a PR should be submitted.
