### ISSUE TITLE
One kafka consumer for messages?

### ISSUE THREAD

**Issue by sherodtaylor** [astronomer/airflow-provider-kafka#9]
Currently for this implementation of `AwaitKafkaMessage` it creates a consumer per operator. Also the operator would need to have a unique consumer group to consume all messages from kafka. Have you found a way to trigger from a long lived consumer process because scaling out to a lot of consumers could have scaling issues.

**Comment by dylanbstorey** [comment]
>Currently for this implementation of AwaitKafkaMessage it creates a consumer per operator.
Yes

>Also the operator would need to have a unique consumer group to consume all messages from kafka.

This is true no matter what and should be provided through the key `group.id`  in the `consumer_config` dictionary. 

>Have you found a way to trigger from a long lived consumer process 

This isn't really possible from Airflow as the execution model is around ephemeral tasks.  But if you've got something in mind PRs are always welcome. 

> because scaling out to a lot of consumers could have scaling issues

Not sure what you mean here. The only scaling scaling in Kafka is through topic partition count as consumers can't exceed that number already. While I'll admit I haven't taken this to any sort of extremes (i.e. thousands of partitions), I have used this exact pattern for hundreds.  I'd suggest that if you're getting to that level of scale, Airflow probably isn't the right avenue for extraction anyways.

**Comment by sherodtaylor** [comment]
The problem is its not really leveraging kafka's ability to scale and split the consumer ideally i'd like to do something like

```
 dag 1 -> defer and create trigger -> consume from kafka  (same consumer group so split messages between each) -> receive message related to dag 2 -> yield event and trigger dag 2
 dag 2 -> defer and create trigger -> consume from kafka (same consumer group so split messages between each)
 ```
 
 so they can share the same consumer group and arbitrarily trigger tasks unrelated to the dag in context? Can you change the context of the dag maybe?

**Comment by dylanbstorey** [comment]
>so they can share the same consumer group and arbitrarily trigger tasks unrelated to the dag in context

just set the same group id if you want them to share the same group. I generally wouldn't suggest this as there's some obvious concerns about potential race conditions causing missed messages as two consumers may leap frog each other on the index.

There's nothing stopping you from defining a workflow that does what you're asking for in the above - including passing index data between DAGs for different consumer groups and maybe creating some `seek` logic.

**Comment by sherodtaylor** [comment]
I'm not asking you to design a workflow but it's a valid design concern because at scale your instantiating a lot of consumers groups and was wondering if you have thought of any ideas around this. Also users of this plugin needs to be aware that you 100% need to have unique group ids to guarantee that you aren't missing messages.
